server:
    host: "jira.etsycorp.com"
    username: ""
    password: ""
    project_key: ""
cloud:
    host: "etsy.atlassian.net"
    email: ""
    api_key: ""
    project_key: ""
custom_fields:  
    # ID: LABEL
user_mappings:
    "server name": "cloud name"
status_mappings:
    "server status": "cloud status"